# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "mps", :force => true do |t|
    t.column "ed_id",                    :string
    t.column "parl_gc_id",               :string
    t.column "parl_gc_constituency_id",  :string
    t.column "constituency_name",        :string
    t.column "party",                    :string
    t.column "name",                     :string
    t.column "email",                    :string
    t.column "website",                  :string
    t.column "parliamentary_phone",      :string
    t.column "parliamentary_fax",        :string
    t.column "preferred_language",       :string
    t.column "constituency_address",     :string
    t.column "constituency_city",        :string
    t.column "constituency_province",    :string
    t.column "constituency_postal_code", :string
    t.column "constituency_phone",       :string
    t.column "constituency_fax",         :string
  end

  create_table "mps_postal_codes", :id => false, :force => true do |t|
    t.column "mp_id",          :integer
    t.column "postal_code_id", :integer
  end

  create_table "postal_codes", :force => true do |t|
    t.column "postal_code", :string
  end

end
